name: Bump version
description: Bump version

inputs:

  version:
    description: Version to bump to
    required: true

  project-framework:
    description: Select what kind of framework the project uses. Note, only Maven is supported at the moment!
    default: Maven
#    options:
#      - Maven
#      - Gradle
#      - NPM
#      - PyPi

  repository:
    description: Bump the version in another repository. If blank, this repository will be bumped
    default: ''

  branch:
    description: Bump a specific branch. If blank, the default master/main branch will be used
    default: ''

  ssh-key:
    description: Only required when checking out another repository
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Prepare environment
      shell: bash
      run: >
        echo "PROJECT_FRAMEWORK="$(echo "${{ inputs.project-framework }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV"
        cat "$GITHUB_ENV"
    - name: Checkout repository and branch
      uses: actions/checkout@v3
      with:
        ssh-key: "${{ inputs.ssh-key }}"
        repository: "${{ inputs.repository }}"
        ref: "${{ inputs.branch }}"
    - name: Bump Maven project version to [${{ inputs.version }}]
      if: env.PROJECT_FRAMEWORK == 'maven'
      shell: bash
      run: >
        mvn -B versions:set "-DnewVersion=${{ inputs.version }}" -DprocessAllModules -DgenerateBackupPoms=false
    - name: Create commit
      shell: bash
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add . && git commit -m "Bumped to version ${{ inputs.version }}"
    - name: Push to remote
      if: inputs.release-branch-enabled == 'true'
      uses: ad-m/github-push-action@v0.6.0
      with:
        repository: "${{ inputs.repository }}"
        branch: "${{ inputs.branch }}"
        github_token: "${{ inputs.ssh-key }}"
        ssh: true
