name: Bump version
description: Bump version

inputs:

  version:
    description: Version to bump to
    required: true

  github-token:
    description: Either use `secrets.GITHUB_TOKEN` for the same repository. Or for other repositories, use a personal access token.
    required: true
    default: ''

  project-framework:
    description: Select what kind of framework the project uses. Note, only Maven is supported at the moment!
    default: Maven
#    options:
#      - Maven
#      - Gradle
#      - NPM
#      - PyPi

  repository:
    description: Bump the version in another repository. If blank, this repository will be bumped
    default: ''

  branch:
    description: Bump a specific branch. If blank, the default master/main branch will be used
    default: ''


runs:
  using: composite
  steps:
    - name: Prepare environment
      shell: bash
      run: |
        echo PROJECT_FRAMEWORK="$(echo "${{ inputs.project-framework }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    - name: Checkout repository and branch
      uses: actions/checkout@v3
      with:
        ssh-key: "${{ inputs.github-token }}"
        repository: "${{ inputs.repository }}"
        ref: "${{ inputs.branch }}"
        persist-credentials: false
        fetch-depth: 0
    - name: Bump version
      uses: actions/github-script@v6
      env:
        projectFramework: "${{ inputs.project-framework }}"
        version: "${{ inputs.version }}"
      with:
        script: |
          const script = require("${{ github.action_path }}/scripts/run-bump-version-command.js");
          script({core, exec});
    - name: Create commit
      shell: bash
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add . && git commit -m "Bumped to version ${{ inputs.version }}"
    - name: Push to remote
      uses: ad-m/github-push-action@master
      with:
        repository: "${{ inputs.repository || '' }}"
        branch: "${{ inputs.branch || '' }}"
        github_token: "${{ inputs.github-token }}"
